# Setup file used by Argyll_Printer_Profiler script.
# Must be located in same folder as script.
# Rules:
#   - Use VARIABLE=value syntax
#   - Quote paths with spaces
#   - No spaces around =
#   - This is “INI-like”, but actually valid Bash

# Configures size of text in terminal window
TERMINAL_FONT_SIZE="12"

# Paths
# Typical printer profile path locations:
# - macOS: "$HOME/Library/ColorSync/Profiles/" (user) or "/Library/ColorSync/Profiles/" (system)
# - Windows: "C:\Windows\System32\spool\drivers\color\" or "%USERPROFILE%\AppData\Local\Microsoft\Windows\spool\drivers\color\"
# - Linux: "/usr/share/color/icc/" or "/var/lib/colord/icc/" or "$HOME/.color/icc/"
# Location of printer profiles where created profile will be copied. This parameter is required.
#PRINTER_PROFILES_PATH="C:\Windows\System32\spool\drivers\color\"
PRINTER_PROFILES_PATH="/Users/knut/Library/ColorSync/Profiles/"
COLOR_SYNC_UTILITY_PATH="/System/Applications/Utilities/ColorSync Utility.app"
# Folder where created/generated icc profiles are stored, with associated files.
CREATED_PROFILES_FOLDER="Created_Profiles"
# Folder where already made / pre-created targets are stored for easy selection
PRE_MADE_TARGETS_FOLDER="Pre-made_Targets"

# PROFILE AND TARGET SETTINGS
# Modify file naming example for desired naming convention/syntax, showed when naming profile under menu choice 1.
EXAMPLE_FILE_NAMING='Printer-MFC-9460-Plain90g-White-sRGB-225Patches-Argyll-CM_2026.01.16'

# Instrument type, affecting how generated targets look. (Not used in argument for targen)
# Valid values:i1 = i1Pro, 3p = i1Pro3+, CM = ColorMunki, 20 = DTP20, 22 = DTP22, 41 = DTP41, 51 = DTP51, SS = SpectroScan
DEFAULT_INSTRUMENT='CM'
# Valid values: true, false. Set to true to auto-open all target images with ColorSync Utility on mac. Applies menu option 1.
ENABLE_AUTO_OPEN_IMAGES_WITH_COLOR_SYNC_MAC='false'

# Note: - Parameters used in arguments for Argyll commands will be ignored if set to empty ('').
#       - Common arguments used for commands (COMMON_ARGUMENTS_??) can be modified as desired.
#         Other argument flags which are programmatically added and changed must not be added
#         to the common arguments parameters.

# ----------------- TARGEN PARAMETERS COMMON FOR ALL MENU OPTIONS -----------------
#           Guide to arguments: https://www.argyllcms.com/doc/targen.html
# ---------------------------------------------------------------------------------
# For INK_LIMIT see under section for COLPROF PARAMETERS
# Typical color space profile (ICC/ICM) locations:
# - macOS: "/System/Library/ColorSync/Profiles/" or "$HOME/Library/ColorSync/Profiles/"
# - Windows: "C:\Windows\System32\spool\drivers\color\" or "C:\Program Files (x86)\Common Files\Adobe\Color\Profiles\"
# - Linux: "/usr/share/color/icc/" or "/usr/local/share/color/icc/" (ArgyllCMS) or "$HOME/.color/icc/"
# Targen Argument -c: Preconditional profile may be .icc or .icm . This parameter can be specified as empty ''.
#PRECONDITIONING_PROFILE_PATH="C:\Windows\System32\spool\drivers\color\sRGB.icm"
PRECONDITIONING_PROFILE_PATH=""
# Targen arguments programmatically selected in menu choice 1 (independent of instrument): -l -e -B -g -m -M -f -c
# Targen arguments used independent of menu selections
COMMON_ARGUMENTS_TARGEN='-v -d2 -G -t'

# ----------------- PRINTTARG PARAMETERS COMMON FOR ALL MENU OPTIONS -----------------
#           Guide to arguments: https://www.argyllcms.com/doc/printtarg.html
# ------------------------------------------------------------------------------------
# Printtarg argument -p: Valid paper values: Letter, A4. Other values results in mismatch of patch count vs. page size.
PAPER_SIZE="A4"
# Printtarg argument -T: Resolution DPI of target image created, such as 200, 300, 600 etc.
TARGET_RESOLUTION='300'
# Printtarg arguments programmatically selected in menu choice 1 (independent of instrument): -i -R -T -p -a -A
# Printtarg arguments used independent of menu selections
# Add -r to prevent randomizing patches
COMMON_ARGUMENTS_PRINTTARG='-v -b -P -m2'

# ----------------- CHARTREAD PARAMETERS COMMON FOR ALL MENU OPTIONS -----------------
#           Guide to arguments: https://www.argyllcms.com/doc/chartread.html
# ------------------------------------------------------------------------------------
# Chartread Argument -T: Consistency of multiple patch readings across a strip. 0.5 to 0.7 is recommended for Colormunki, depending on printer type.
STRIP_PATCH_CONSISTENSY_TOLERANCE='0.7'
# Chartread arguments used in menu choice 1+2+3: -r -T
# Chartread arguments used independent of menu selections
COMMON_ARGUMENTS_CHARTREAD='-v -H -B -S'

# ----------------- COLPROF PARAMETERS COMMON FOR ALL MENU OPTIONS -----------------
#           Guide to arguments: https://www.argyllcms.com/doc/colprof.html
# ----------------------------------------------------------------------------------
# Typical color space profile (ICC/ICM) locations:
# - macOS: "/System/Library/ColorSync/Profiles/" or "$HOME/Library/ColorSync/Profiles/"
# - Windows: "C:\Windows\System32\spool\drivers\color\" or "C:\Program Files (x86)\Common Files\Adobe\Color\Profiles\"
# - Linux: "/usr/share/color/icc/" or "/usr/local/share/color/icc/" (ArgyllCMS) or "$HOME/.color/icc/"
# ICC profile
# Profile may be .icc or .icm . This parameter is required.
#PRINTER_ICC_PATH="C:\Windows\System32\spool\drivers\color\sRGB.icm"
PRINTER_ICC_PATH="/System/Library/ColorSync/Profiles/AdobeRGB1998.icc"
# Argument -l in targen AND colprof: Targen specifies ink limit of 300 if not defined (argyllcms 3.4.1, but fixed from 3.5.0), Specify empty ('') to prevent limiting (such as for laser printers).
INK_LIMIT=""
# Argument -r in Colprof average deviation, affecting accuracy and smooting of profile. Argyll-default 0.5. 1.0 makes smoother profile without much reduction in accuracy.
PROFILE_SMOOTHING='1.0'
# Colprof arguments used in menu choice 1+2+3+4: -l -r -S -D
# Colprof arguments used independent of menu selections
COMMON_ARGUMENTS_COLPROF='-v -qh -cmt -dpp'

# ----------------- MENU PARAMETERS TARGEN OPTIMIZED FOR COLORMUNKI: USED IF PAGE SIZE A4 OR LETTER -----------------
# ----------------- USED IF: INSTRUMENT COLORMUNKI, PAGE SIZE A4 OR LETTER -----------------
INST_CM_MENU_OPTION1_A4_DESCRIPTION=' - Small  – 1 x A4 page,  quick profiling'
INST_CM_MENU_OPTION2_A4_DESCRIPTION=' - Medium – 2 x A4 pages, recommended minimum'
INST_CM_MENU_OPTION3_A4_DESCRIPTION=' - Large  – 3 x A4 pages, better accuracy'
INST_CM_MENU_OPTION4_A4_DESCRIPTION=' - XL     – 4 x A4 pages, high quality'
INST_CM_MENU_OPTION5_A4_DESCRIPTION='- XXL    – 5 x A4 pages, very high quality'
INST_CM_MENU_OPTION6_A4_DESCRIPTION='- XXXL   – 6 x A4 pages, maximum quality'

INST_CM_MENU_OPTION1_LETTER_DESCRIPTION=' - Small  - 1 x Letter page,  quick profiling'
INST_CM_MENU_OPTION2_LETTER_DESCRIPTION=' - Medium - 2 x Letter pages, recommended minimum'
INST_CM_MENU_OPTION3_LETTER_DESCRIPTION=' - Large  - 3 x Letter pages, better accuracy'
INST_CM_MENU_OPTION4_LETTER_DESCRIPTION=' - XL     - 4 x Letter pages, high quality'
INST_CM_MENU_OPTION5_LETTER_DESCRIPTION=' - XXL    - 5 x Letter pages, very high quality'
INST_CM_MENU_OPTION6_LETTER_DESCRIPTION='- XXXL   - 6 x Letter pages, maximum quality'

INST_CM_MENU_OPTION1_PATCH_COUNT_A4_f='210'         # SPECIFY NUMBER ONLY. EMPTY STRING WHEN NOT USED
INST_CM_MENU_OPTION2_PATCH_COUNT_A4_f='420'
INST_CM_MENU_OPTION3_PATCH_COUNT_A4_f='630'
INST_CM_MENU_OPTION4_PATCH_COUNT_A4_f='840'
INST_CM_MENU_OPTION5_PATCH_COUNT_A4_f='1050'
INST_CM_MENU_OPTION6_PATCH_COUNT_A4_f='1260'

INST_CM_MENU_OPTION1_PATCH_COUNT_LETTER_f='196'     # SPECIFY NUMBER ONLY. EMPTY STRING WHEN NOT USED
INST_CM_MENU_OPTION2_PATCH_COUNT_LETTER_f='392'
INST_CM_MENU_OPTION3_PATCH_COUNT_LETTER_f='588'
INST_CM_MENU_OPTION4_PATCH_COUNT_LETTER_f='784'
INST_CM_MENU_OPTION5_PATCH_COUNT_LETTER_f='980'
INST_CM_MENU_OPTION6_PATCH_COUNT_LETTER_f='1176'

INST_CM_MENU_OPTION1_WHITE_PATCHES_e='5'            # SPECIFY NUMBER ONLY. EMPTY STRING WHEN NOT USED
INST_CM_MENU_OPTION2_WHITE_PATCHES_e='6'
INST_CM_MENU_OPTION3_WHITE_PATCHES_e='7'
INST_CM_MENU_OPTION4_WHITE_PATCHES_e='8'
INST_CM_MENU_OPTION5_WHITE_PATCHES_e='9'
INST_CM_MENU_OPTION6_WHITE_PATCHES_e='10'

INST_CM_MENU_OPTION1_BLACK_PATCHES_B='5'            # SPECIFY NUMBER ONLY. EMPTY STRING WHEN NOT USED
INST_CM_MENU_OPTION2_BLACK_PATCHES_B='6'
INST_CM_MENU_OPTION3_BLACK_PATCHES_B='7'
INST_CM_MENU_OPTION4_BLACK_PATCHES_B='8'
INST_CM_MENU_OPTION5_BLACK_PATCHES_B='9'
INST_CM_MENU_OPTION6_BLACK_PATCHES_B='10'

INST_CM_MENU_OPTION1_GRAY_STEPS_g='42'              # APPROX 20% OF PATCH COUNT FOR A4
INST_CM_MENU_OPTION2_GRAY_STEPS_g='84'              # SPECIFY NUMBER ONLY. EMPTY STRING WHEN NOT USED
INST_CM_MENU_OPTION3_GRAY_STEPS_g='126'
INST_CM_MENU_OPTION4_GRAY_STEPS_g='168'
INST_CM_MENU_OPTION5_GRAY_STEPS_g='210'
INST_CM_MENU_OPTION6_GRAY_STEPS_g='252'

INST_CM_MENU_OPTION1_MULTI_CUBE_STEPS_m=''          # SPECIFY NUMBER ONLY. EMPTY STRING WHEN NOT USED
INST_CM_MENU_OPTION2_MULTI_CUBE_STEPS_m=''
INST_CM_MENU_OPTION3_MULTI_CUBE_STEPS_m=''
INST_CM_MENU_OPTION4_MULTI_CUBE_STEPS_m=''
INST_CM_MENU_OPTION5_MULTI_CUBE_STEPS_m=''
INST_CM_MENU_OPTION6_MULTI_CUBE_STEPS_m=''

INST_CM_MENU_OPTION1_MULTI_CUBE_SURFACE_STEPS_M=''  # SPECIFY NUMBER ONLY. EMPTY STRING WHEN NOT USED
INST_CM_MENU_OPTION2_MULTI_CUBE_SURFACE_STEPS_M=''
INST_CM_MENU_OPTION3_MULTI_CUBE_SURFACE_STEPS_M=''
INST_CM_MENU_OPTION4_MULTI_CUBE_SURFACE_STEPS_M=''
INST_CM_MENU_OPTION5_MULTI_CUBE_SURFACE_STEPS_M=''
INST_CM_MENU_OPTION6_MULTI_CUBE_SURFACE_STEPS_M=''

INST_CM_MENU_OPTION1_SCALE_PATCH_AND_SPACER_a=''    # SPECIFY NUMBER ONLY (dot as decimal). EMPTY STRING WHEN NOT USED
INST_CM_MENU_OPTION2_SCALE_PATCH_AND_SPACER_a=''
INST_CM_MENU_OPTION3_SCALE_PATCH_AND_SPACER_a=''
INST_CM_MENU_OPTION4_SCALE_PATCH_AND_SPACER_a=''
INST_CM_MENU_OPTION5_SCALE_PATCH_AND_SPACER_a=''
INST_CM_MENU_OPTION6_SCALE_PATCH_AND_SPACER_a=''

INST_CM_MENU_OPTION1_SCALE_SPACER_A=''    # SPECIFY NUMBER ONLY (dot as decimal). EMPTY STRING WHEN NOT USED
INST_CM_MENU_OPTION2_SCALE_SPACER_A=''
INST_CM_MENU_OPTION3_SCALE_SPACER_A=''
INST_CM_MENU_OPTION4_SCALE_SPACER_A=''
INST_CM_MENU_OPTION5_SCALE_SPACER_A=''
INST_CM_MENU_OPTION6_SCALE_SPACER_A=''

# ----------------- MENU PARAMETERS TARGEN OPTIMIZED FOR NON-COLORMUNKI INSTRUMENTS -----------------
# ----------------- USED IF: INSTRUMENT NOT COLORMUNKI, PAGE SIZE INDEPENDENT -----------------
# ----------------- BUT ALSO USED IF: INSTRUMENT COLORMUNKI AND PAGE SIZE IS NOT A4 OR LETTER -----------------
INST_OTHER_MENU_OPTION1_DESCRIPTION=' - i1Pro Small  – 1 x A4 page,     quick profiling'
INST_OTHER_MENU_OPTION2_DESCRIPTION=' - i1Pro Small  – 1 x Letter page, quick profiling'
INST_OTHER_MENU_OPTION3_DESCRIPTION=' - i1Pro Medium – 1 x A4 page,     recommended default'
INST_OTHER_MENU_OPTION4_DESCRIPTION=' - i1Pro Medium – 1 x Letter page, recommended default'
INST_OTHER_MENU_OPTION5_DESCRIPTION='- i1Pro Large  - 3 x A4 pages, better accuracy'
INST_OTHER_MENU_OPTION6_DESCRIPTION='- i1Pro Large  - 3 x Letter pages, better accuracy'

INST_OTHER_MENU_OPTION1_PATCH_COUNT_f='480'     # SPECIFY NUMBER ONLY. EMPTY STRING WHEN NOT USED
INST_OTHER_MENU_OPTION2_PATCH_COUNT_f='480'
INST_OTHER_MENU_OPTION3_PATCH_COUNT_f='957'
INST_OTHER_MENU_OPTION4_PATCH_COUNT_f='957'
INST_OTHER_MENU_OPTION5_PATCH_COUNT_f='2250'
INST_OTHER_MENU_OPTION6_PATCH_COUNT_f='2250'

INST_OTHER_MENU_OPTION1_WHITE_PATCHES_e='6'     # SPECIFY NUMBER ONLY. EMPTY STRING WHEN NOT USED
INST_OTHER_MENU_OPTION2_WHITE_PATCHES_e='6'
INST_OTHER_MENU_OPTION3_WHITE_PATCHES_e='2'
INST_OTHER_MENU_OPTION4_WHITE_PATCHES_e='2'
INST_OTHER_MENU_OPTION5_WHITE_PATCHES_e='8'
INST_OTHER_MENU_OPTION6_WHITE_PATCHES_e='8'

INST_OTHER_MENU_OPTION1_BLACK_PATCHES_B='5'     # SPECIFY NUMBER ONLY. EMPTY STRING WHEN NOT USED
INST_OTHER_MENU_OPTION2_BLACK_PATCHES_B='5'
INST_OTHER_MENU_OPTION3_BLACK_PATCHES_B='2'
INST_OTHER_MENU_OPTION4_BLACK_PATCHES_B='2'
INST_OTHER_MENU_OPTION5_BLACK_PATCHES_B='8'
INST_OTHER_MENU_OPTION6_BLACK_PATCHES_B='8'

INST_OTHER_MENU_OPTION1_GRAY_STEPS_g='128'       # APPROX 20% OF PATCH COUNT
INST_OTHER_MENU_OPTION2_GRAY_STEPS_g='128'       # SPECIFY NUMBER ONLY. EMPTY STRING WHEN NOT USED
INST_OTHER_MENU_OPTION3_GRAY_STEPS_g='24'
INST_OTHER_MENU_OPTION4_GRAY_STEPS_g='24'
INST_OTHER_MENU_OPTION5_GRAY_STEPS_g='128'
INST_OTHER_MENU_OPTION6_GRAY_STEPS_g='128'

INST_OTHER_MENU_OPTION1_MULTI_CUBE_STEPS_m=''  # SPECIFY NUMBER ONLY. EMPTY STRING WHEN NOT USED
INST_OTHER_MENU_OPTION2_MULTI_CUBE_STEPS_m=''
INST_OTHER_MENU_OPTION3_MULTI_CUBE_STEPS_m=''
INST_OTHER_MENU_OPTION4_MULTI_CUBE_STEPS_m=''
INST_OTHER_MENU_OPTION5_MULTI_CUBE_STEPS_m=''
INST_OTHER_MENU_OPTION6_MULTI_CUBE_STEPS_m=''

INST_OTHER_MENU_OPTION1_MULTI_CUBE_SURFACE_STEPS_M=''  # SPECIFY NUMBER ONLY. EMPTY STRING WHEN NOT USED
INST_OTHER_MENU_OPTION2_MULTI_CUBE_SURFACE_STEPS_M=''
INST_OTHER_MENU_OPTION3_MULTI_CUBE_SURFACE_STEPS_M=''
INST_OTHER_MENU_OPTION4_MULTI_CUBE_SURFACE_STEPS_M=''
INST_OTHER_MENU_OPTION5_MULTI_CUBE_SURFACE_STEPS_M=''
INST_OTHER_MENU_OPTION6_MULTI_CUBE_SURFACE_STEPS_M=''

INST_OTHER_MENU_OPTION1_SCALE_PATCH_AND_SPACER_a='1.05' # SPECIFY NUMBER ONLY. EMPTY STRING WHEN NOT USED
INST_OTHER_MENU_OPTION2_SCALE_PATCH_AND_SPACER_a='1.03'
INST_OTHER_MENU_OPTION3_SCALE_PATCH_AND_SPACER_a='0.75'
INST_OTHER_MENU_OPTION4_SCALE_PATCH_AND_SPACER_a='0.74'
INST_OTHER_MENU_OPTION5_SCALE_PATCH_AND_SPACER_a='0.85'
INST_OTHER_MENU_OPTION6_SCALE_PATCH_AND_SPACER_a='0.84'

INST_OTHER_MENU_OPTION1_SCALE_SPACER_A='0.6'    # SPECIFY NUMBER ONLY (dot as decimal). EMPTY STRING WHEN NOT USED
INST_OTHER_MENU_OPTION2_SCALE_SPACER_A='0.6'
INST_OTHER_MENU_OPTION3_SCALE_SPACER_A='0.5'
INST_OTHER_MENU_OPTION4_SCALE_SPACER_A='0.5'
INST_OTHER_MENU_OPTION5_SCALE_SPACER_A='0.6'
INST_OTHER_MENU_OPTION6_SCALE_SPACER_A='0.6'

# ----------------- MENU PARAMETERS PRINTTARG-----------------
# ----------------- USED INDEPENDENT OF INSTRUMENT OR PAGE SIZE -----------------
# Set if layout seed (-R argument) shall be used to keep same target layout between chart generations. Valid values: 'true' or 'false'.
USE_LAYOUT_SEED_FOR_TARGET='false'
MENU_OPTION1_LAYOUT_SEED_R='866'      #NOT USED IF USE_LAYOUT_SEED_FOR_TARGET IS FALSE
MENU_OPTION2_LAYOUT_SEED_R='866'      # SPECIFY NUMBER ONLY.
MENU_OPTION3_LAYOUT_SEED_R='866'
MENU_OPTION4_LAYOUT_SEED_R='866'
MENU_OPTION5_LAYOUT_SEED_R='866'
MENU_OPTION6_LAYOUT_SEED_R='866'


